name: Build and push Docker images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-ecommerce-backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:${{ github.sha }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./docker-ecommerce-frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:${{ github.sha }}
